# values file for nfs-metrics-exporter deployment using Helm.

fullnameOverride: ""
nameOverride: ""

# base image configuration
image:
  repository: ghcr.io/amirhnajafiz/nfs-metrics-exporter
  pullPolicy: IfNotPresent
  tag: "master"

# node selector configuration
nodeSelector:
  node-role.kubernetes.io/worker: "worker"
  kubernetes.io/nfsiostat-enabled: "true"

# tolerations configuration
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: "master"
    effect: "NoSchedule"

# service configuration
service:
  type: ClusterIP
  port: 80

# serviceMonitor configuration
serviceMonitor:
  enabled: true
  namespace: ""
  interval: ""
  scrapeTimeout: ""

# resources configuration
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# exporter configuration
config:
  # debugging settings
  debug_mode: true
  # exporter interval for running the nfsiostat (in seconds)
  export_interval: 5
  # exporter HTTP server port
  service_port: 5050
  # service secret key (MD5 hash will be generated from this key)
  secret_key: "mykey"
