# values file for nfs-metrics-exporter deployment using Helm.

fullnameOverride: ""
nameOverride: ""

image:
  repository: ghcr.io/amirhnajafiz/nfs-metrics-exporter
  pullPolicy: IfNotPresent
  tag: "master"
