run:
  timeout: 2m
  deadline: 5m
  issues-exit-code: 1 # exit with error if issues are found

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - revive
    - gosimple
    - unused
    - bodyclose
    - gocyclo
  fast: true # optimize speed

issues:
  exclude:
    - "G104" # exclude gosec rule G104 (CWE-703: Errors unhandled)

output:
  format: colored-line-number
  print-issued-lines: true
  uniq-by-line: true
