name: lint

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'  # match your Go version
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v2.0.2  # explicit version for stability
          args: --format=github-actions ./...  # critical fix here (from v.1.X to v.2.X)
