name: Build and push Docker image to GitHub Container Registry

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v6
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          TAG: ${{ github.ref_name }}
        with:
          push: true
          files: "build/docker-bake.json"
      - uses: docker/bake-action@v6
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          push: true
          files: "build/docker-bake.json"
